#this is my bio
names=('amarachi','favour','chinonso')
print(names)
age=(17)
print(age)
hobbies=('eating','watching movies','listening to music')
print(hobbies)
favouritecolours=('blue','yellow')
print(favouritecolours)
favouritefruits=('mango','grape')
print(favouritefruits)
e_mail=('amichino2005@gmail.com')
print(e_mail)
password=('amichino2005')
print(password)